gems:
  - jekyll-sitemap


# Site settings
title: Lila Villas
email: info@lilavillas.gr
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/lilavillas" # the subpath of your site, e.g. /blog/
url: "lilavillas.gr" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Compress layout - Settings
compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []
    
collections:
  rooms:
    output: true
    permalink: /rooms/:path
    
defaults:
  - scope:
      path: ""
      type: rooms
    values:
      layout: default    